# Generated by Django 5.2 on 2025-05-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
