# Generated by Django 5.2 on 2025-06-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_annualcoursedistribution_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='academic_year',
            field=models.CharField(default=-1, max_length=10),
            preserve_default=False,
        ),
    ]
