# Generated by Django 5.2 on 2025-05-28 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_center_affiliated_to_center_association_and_more'),
        ('programs', '0002_trainingprograme_logo'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contarct_with', models.CharField(choices=[('entraide', 'Entraide'), ('association', 'Association')], max_length=20)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='centers.center')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='programs.trainingprograme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
