# Generated by Django 5.2 on 2025-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_center_affiliated_to_center_association_and_more'),
        ('teachers', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='centers.group'),
        ),
    ]
