# Generated by Django 5.2 on 2025-07-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        # First, remove the old unique_together constraint
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        # Add the new section field
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.section'),
            preserve_default=False,
        ),
        # Add the about field to section
        migrations.AddField(
            model_name='section',
            name='about',
            field=models.TextField(blank=True),
        ),
        # Remove the old learn field
        migrations.RemoveField(
            model_name='lesson',
            name='learn',
        ),
        # Delete the Learn model
        migrations.DeleteModel(
            name='Learn',
        ),
        # Finally, add the new unique_together constraint
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('section', 'order')},
        ),
    ]
