# Generated by Django 5.2 on 2025-07-04 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_unique_together_lesson_section_and_more'),
        ('programs', '0004_trainingcourse_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_program', to='programs.trainingprograme'),
        ),
    ]
