# Generated by Django 5.2 on 2025-07-04 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_program'),
        ('programs', '0004_trainingcourse_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_program', to='programs.trainingprograme'),
            preserve_default=False,
        ),
    ]
