# Generated by Django 5.2 on 2025-06-09 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_center_affiliated_to_center_association_and_more'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule_session',
            options={'ordering': ['day', 'start_time'], 'verbose_name': 'Weekly Schedule Template', 'verbose_name_plural': 'Weekly Schedule Templates'},
        ),
        migrations.AddField(
            model_name='schedule_session',
            name='academic_year',
            field=models.CharField(default='2024-2025', help_text='e.g., 2024-2025', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule_session',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to disable this weekly session'),
        ),
        migrations.AddField(
            model_name='schedule_session',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='schedule_session',
            unique_together={('room', 'day', 'start_time', 'academic_year'), ('trainer', 'day', 'start_time', 'academic_year')},
        ),
        migrations.CreateModel(
            name='SessionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_date', models.DateField()),
                ('custom_start_time', models.TimeField(blank=True, null=True)),
                ('custom_end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Reason for cancellation/changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.room')),
                ('custom_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='schedule.schedule_session')),
            ],
            options={
                'verbose_name': 'Session Instance',
                'verbose_name_plural': 'Session Instances',
                'ordering': ['specific_date', 'schedule_template__start_time'],
                'unique_together': {('schedule_template', 'specific_date')},
            },
        ),
    ]
