// MainPage.tsx
import { Button } from "@/components/ui/button";
import { useNavigate } from 'react-router-dom';

// Generated by Copilot
const MainPage = () => {
  const navigate = useNavigate();

  const handleLoginClick = () => {
    navigate('/login');
  };

  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-gray-100 to-gray-200 dark:from-gray-900 dark:to-gray-800 px-4">
      <div className="max-w-4xl mx-auto text-center">
        <h1 className="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-6">
          Entraide National Management System
        </h1>
        <p className="text-xl text-gray-700 dark:text-gray-300 mb-8 max-w-2xl mx-auto">
          A comprehensive platform for managing centers, associations, trainers, students, and programs.
        </p>
        
        <div className="space-y-4 md:space-y-0 md:space-x-4 flex flex-col md:flex-row justify-center">
          <Button
            className="px-8 py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-medium rounded-lg text-lg dark:bg-indigo-700 dark:hover:bg-indigo-600"
            onClick={handleLoginClick}
          >
            Login
          </Button>
          <Button
            className="px-8 py-3 bg-white hover:bg-gray-100 text-indigo-600 font-medium rounded-lg text-lg border border-indigo-600 dark:bg-gray-800 dark:hover:bg-gray-700 dark:text-indigo-400 dark:border-indigo-500"
            variant="outline"
          >
            Learn More
          </Button>
        </div>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto mt-16">
        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Centers and Associations</h2>
          <p className="text-gray-600 dark:text-gray-400">
            Manage centers and associations efficiently with our comprehensive administrative tools.
          </p>
        </div>
        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Teachers and Training</h2>
          <p className="text-gray-600 dark:text-gray-400">
            Organize classes, manage teacher schedules, and track curriculum progress seamlessly.
          </p>
        </div>
        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Student Management</h2>
          <p className="text-gray-600 dark:text-gray-400">
            Track student attendance, performance, and progress through their educational journey.
          </p>
        </div>
      </div>
    </div>
  );
};

export default MainPage;