# Generated by Django 5.2 on 2025-05-07 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='affiliated_to',
            field=models.CharField(blank=True, choices=[('entraide', 'Entraide Nationale'), ('association', 'Association'), ('other', 'Other')], default='entraide', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='associations.association'),
        ),
        migrations.AddField(
            model_name='center',
            name='other_affiliation',
            field=models.CharField(blank=True, help_text="Specify if 'affiliated_to' is 'Other'", max_length=255, null=True),
        ),
    ]
