import { BrowserRouter as Router, Routes, Route, Navigate } from "react-router-dom"
import MainPage from "./pages/MainPage"
import LoginPage from "./pages/auth/LoginPage"
import AdminDashboard from "./pages/dashboards/admin/AdminDashboard"
import CenterSupervisorDashboard from "./pages/dashboards/center/CenterSupervisorDashboard"
import AssociationSupervisorDashboard from "./pages/dashboards/association/AssociationSupervisorDashboard"
import TrainerDashboard from "./pages/dashboards/trainer/TrainerDashboard"
import StudentDashboard from "./pages/dashboards/student/StudentDashboard"
import { AuthProvider } from "./contexts/AuthContext"
import ProtectedRoute from "./components/auth/ProtectedRoute"

// Generated by Copilot
function App() {
  return (
    <AuthProvider>
      <Router>
        <Routes>
          {/* Public Routes */}
          <Route path="/" element={<MainPage />} />
          <Route path="/login" element={<LoginPage />} />
          
          {/* Protected Dashboard Routes - Only accessible to users with the correct role */}
          <Route path="/dashboard/admin" element={
            <ProtectedRoute allowedRoles={['admin']}>
              <AdminDashboard />
            </ProtectedRoute>
          } />
          
          <Route path="/dashboard/center" element={
            <ProtectedRoute allowedRoles={['center_supervisor']}>
              <CenterSupervisorDashboard />
            </ProtectedRoute>
          } />
          
          <Route path="/dashboard/association" element={
            <ProtectedRoute allowedRoles={['association_supervisor']}>
              <AssociationSupervisorDashboard />
            </ProtectedRoute>
          } />
          
          <Route path="/dashboard/trainer" element={
            <ProtectedRoute allowedRoles={['trainer']}>
              <TrainerDashboard />
            </ProtectedRoute>
          } />
          
          <Route path="/dashboard/student" element={
            <ProtectedRoute allowedRoles={['student']}>
              <StudentDashboard />
            </ProtectedRoute>
          } />
          
          {/* Fallback route */}
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </Router>
    </AuthProvider>
  )
}

export default App
