# Generated by Django 5.2 on 2025-06-09 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('schedule', '0002_alter_schedule_session_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance_record',
            options={'ordering': ['date', 'session_template__start_time'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.RemoveField(
            model_name='attendance_record',
            name='session',
        ),
        migrations.AddField(
            model_name='attendance_record',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about attendance'),
        ),
        migrations.AddField(
            model_name='attendance_record',
            name='session_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.sessioninstance'),
        ),
        migrations.AddField(
            model_name='attendance_record',
            name='session_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule_session'),
        ),
    ]
