# Generated by Django 5.2 on 2025-06-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_record_options_and_more'),
        ('schedule', '0002_alter_schedule_session_options_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance_record',
            unique_together={('student', 'session_instance', 'date'), ('student', 'session_template', 'date')},
        ),
    ]
